version: '3.4'

services:
  reportgeneration:
    image: reportgeneration
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn sleep 50000:app --host 0.0.0.0 --port 6060"]
    ports:
      - 6060:6060
      - 5678:5678
